Update version_checker.yml

diff --git a/.github/workflows/version_checker.yml b/.github/workflows/version_checker.yml
--- a/.github/workflows/version_checker.yml
+++ b/.github/workflows/version_checker.yml
@@ -32,11 +32,14 @@ jobs:
 
       - name: Update stored_version.txt
         run: |
-          git fetch # Fetch the latest changes from the main branch
-          git rebase # Rebase the changes on top of the latest main branch
-          echo "${{ steps.get_version.outputs.latest_version }}" > stored_version.txt
-          git add stored_version.txt
-          git commit -m "Update stored_version.txt to ${{ steps.get_version.outputs.latest_version }}" --allow-empty || true
+          # Fetch the latest changes from the main branch
+          git fetch origin main || true
+          
+          # Rebase the changes on top of the latest main branch
+          git rebase origin/main || true
+          
+          # Check if there are changes to commit
+          git diff --quiet || git commit -m "Update stored_version.txt to ${{ steps.get_version.outputs.latest_version }}"
           
           # Fetch again to make sure there are no new changes
           git fetch origin main
@@ -44,4 +47,5 @@ jobs:
           # If any new changes, rebase and resolve conflicts if necessary
           git rebase origin/main
           
+          # Push changes to the main branch and set exit code
           git push origin main || exit 1
